sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t trinuyen1099/docker-react -f Dockerfile.dev .

script:
  # - docker run -e CI=true trinuyen1099/docker-react npm run test
  - docker run trinuyen1099/docker-react npm run test -- --coverage